// npm run simulate: runs the deterministic balance simulator and writes
// BALANCE_REPORT.md (milestones, targets, stalls, energy over time).
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { PACING_TARGETS, STALL_HOURS } from '../src/data/pacingTargets';
import { DEFAULT_SIM, runBalanceSim } from '../src/sim/balanceSim';
import { formatNumber } from '../src/utils/format';
import { getPlayerLevel } from '../src/utils/playerLevel';
import pkg from '../package.json';

const started = Date.now();
const r = runBalanceSim({}, STALL_HOURS);
const ms = Date.now() - started;
const h = (x: number) => (x < 1 ? `${Math.round(x * 60)} min` : `${x.toFixed(1)} h`);
const byId = new Map(r.milestones.map((m) => [m.id, m]));

const targetRows = PACING_TARGETS.map((t) => {
  const m = byId.get(t.id);
  const [lo, hi] = t.hours;
  const range = `${h(lo)} – ${Number.isFinite(hi) ? h(hi) : '∞'}`;
  if (!m) return `| ${t.label} | ${range} | not reached in ${h(r.hours)} | ❌ |`;
  const ok = m.hours >= lo * 0.7 && m.hours <= hi * 1.3;
  return `| ${t.label} | ${range} | ${h(m.hours)} | ${ok ? '✅' : '⚠️'} |`;
});

const report = `# Balance report

Generated by \`npm run simulate\` for v${pkg.version} in ${ms} ms. Deterministic: the same data always gives the same report.

**Player model:** greedy and idle-heavy. Clicks ${DEFAULT_SIM.clicksPerSecond}/s for the first ${DEFAULT_SIM.clickMinutes} minutes, then never again. Decides every ${DEFAULT_SIM.stepSeconds} s for the first ${DEFAULT_SIM.lateFromHours} h, then every ${DEFAULT_SIM.lateStepSeconds} s:
1. Start the affordable research that unlocks something (or else the quickest one).
2. Build the unlocked generator with the most energy per room that it can afford and fuel, scrapping weaker generators when room is short.
3. Buy a producer for whatever resource blocks its next build.
4. Expand room when it is nearly full.

A real player who clicks more or plans better will be faster.

## Summary

- Simulated: **${h(r.hours)}**, ending at **${Math.round(r.completion * 100)}% completion**.
- Stalls (more than ${STALL_HOURS} h with no new milestone): ${r.gaps.length === 0 ? 'none' : r.gaps.map(([a, b]) => `${h(a)} → ${h(b)}`).join(', ')}.

## Targets

✅ within range (±30%) · ⚠️ outside · ❌ not reached. Targets live in \`src/data/pacingTargets.ts\`; owner playtest feedback overrides them.

| Target | Range | Simulated | |
|---|---|---|---|
${targetRows.join('\n')}

## Milestones

| Time | Milestone |
|---|---|
${r.milestones.filter((m) => !/^(level\d+|plevel|contracts5|petYoung|ach):/.test(m.id)).map((m) => `| ${h(m.hours)} | ${m.label} |`).join('\n')}

## Energy over time

| Time | Energy/s | Completion | Room | Player level |
|---|---|---|---|---|
${r.samples
  .filter((_, i, a) => i % Math.max(1, Math.floor(a.length / 20)) === 0 || i === a.length - 1)
  .map((x) => `| ${h(x.hours)} | ${formatNumber(x.energyPerSecond, 'short', 1)} | ${Math.round(x.completion * 100)}% | ${x.room} | ${getPlayerLevel(x.lifetimeEnergy).level} |`)
  .join('\n')}

## Notes and changes

See the "Tuning log" section below; new runs keep it.
`;

const path = resolve(import.meta.dirname, '..', 'BALANCE_REPORT.md');
let log = '';
try {
  const old = (await import('node:fs')).readFileSync(path, 'utf8');
  const i = old.indexOf('## Tuning log');
  if (i >= 0) log = old.slice(i);
} catch {
  // first run
}
writeFileSync(path, report + '\n' + (log || '## Tuning log\n\n(no changes yet)\n'));
console.log(`BALANCE_REPORT.md written: ${h(r.hours)} simulated, ${Math.round(r.completion * 100)}% completion, ${r.gaps.length} stalls, ${ms} ms.`);
